- added task 1
serghovhannisyan/egs-intern pull request #5
Opened 2020-03-24 17:39 UTC by 1994arsensargsyan1994

2020-03-24 17:55 UTC, serghovhannisyan commented on arsen-sargsyan-resources/readFile
> +arsen hello barev nidodon hello
maybe there is a way to put this file inside your package?

2020-03-24 18:03 UTC, M-Suzy commented on src/com/egs/arsensargsyan/task1/ReadHello.java
> +    private Map<Integer, Integer> resultMap = new HashMap<>();
I think you don't need a Map for this problem.

2020-03-24 18:08 UTC, M-Suzy commented on src/com/egs/arsensargsyan/task1/ReadHello.java
> +            resultMap = read("hello");
Keep hello as const

2020-03-26 07:08 UTC, serghovhannisyan approved these changes

2020-03-26 07:10 UTC, serghovhannisyan requested changes
arsen-sargsyan-resources/ folder still there

2020-03-26 14:43 UTC, serghovhannisyan approved these changes

2020-03-26 14:43 UTC, merged